# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Product.create([{ product_name: 'Plan Inical Bodykey Chocolate', url_image: '~/workspace/app/assets/image.png', catalog_price: 2746.0, points: 101.50, product_line: 'BodyKey'},
                { product_name: 'Plan Inical Bodykey Fresa', url_image: '~/workspace/app/assets/image.png', catalog_price: 2746.0, points: 101.50, product_line: 'BodyKey'},
                { product_name: 'BodyKey Carb Sensitive Chocolate', url_image: '~/workspace/app/assets/image.png', catalog_price: 1245.0, points: 41.88, product_line: 'BodyKey'},
                { product_name: 'Bodykey Carb Sensitive Fresa', url_image: '~/workspace/app/assets/image.png', catalog_price: 1245.0, points: 41.0, product_line: 'BodyKey'},
                { product_name: 'Bodykey Fat Sensitive Chocolate', url_image: '~/workspace/app/assets/image.png', catalog_price: 1460.0, points: 49.44, product_line: 'BodyKey'},
                { product_name: 'Bodykey Fat Sensitive Fresa', url_image: '~/workspace/app/assets/image.png', catalog_price: 1460.0, points: 49.44, product_line: 'BodyKey'},
                { product_name: 'Bodykey Shake Plus Chocolate', url_image: '~/workspace/app/assets/image.png', catalog_price: 659.0, points: 21.26, product_line: 'BodyKey'},
                { product_name: 'Bodykey Shake Plus Fresa', url_image: '~/workspace/app/assets/image.png', catalog_price: 659.0, points: 21.26, product_line: 'BodyKey'},
                { product_name: 'Bodykey Herbal Mix', url_image: '~/workspace/app/assets/image.png', catalog_price: 469.0, points: 16.48, product_line: 'BodyKey'},
                { product_name: 'Green Advanced', url_image: '~/workspace/app/assets/image.png', catalog_price: 440.0, points: 15.46, product_line: 'BodyKey'},
                { product_name: 'Cerocarb', url_image: '~/workspace/app/assets/image.png', catalog_price: 275.0, points: 9.67, product_line: 'Nutrilite'},
                { product_name: 'CLA 500', url_image: '~/workspace/app/assets/image.png', catalog_price: 569.0, points: 20.0, product_line: 'Nutrilite'},
                { product_name: 'Proteina Vegetal en Polvo', url_image: '~/workspace/app/assets/image.png', catalog_price: 479.0, points: 16.83, product_line: 'Nutrilite'},
                { product_name: 'Paquete Alimentacion en Balance', url_image: '~/workspace/app/assets/image.png', catalog_price: 999.0, points: 35.11, product_line: 'Nutrilite'},
                { product_name: 'Paquete Mujer en equilibrio', url_image: '~/workspace/app/assets/', catalog_price: 799.0, points: 28.08, product_line: 'Nutrilite'},
                { product_name: 'Paquete Energia Activa', url_image: '~/workspace/app/assets/', catalog_price: 999.0, points: 35.11, product_line: 'Nutrilite'},
                { product_name: 'Paquete Perfecto', url_image: '~/workspace/app/assets/', catalog_price: 1650.0, points: 57.99, product_line: 'Nutrilite'},
                { product_name: 'Paquete Mantente en Circulacion', url_image: '~/workspace/app/assets/', catalog_price: 840.0, points: 29.52, product_line: 'Nutrilite'},
                { product_name: 'Complejo Omega 3 90 Cap', url_image: '~/workspace/app/assets/', catalog_price: 645.0, points: 22.67, product_line: 'Nutrilite'},
                { product_name: 'Complejo Omega 3 30 Cap', url_image: '~/workspace/app/assets/', catalog_price: 269.0, points: 9.45, product_line: 'Nutrilite'},
                { product_name: 'Ajo Concentrado', url_image: '~/workspace/app/assets/', catalog_price: 385.0, points: 13.53, product_line: 'Nutrilite'},
                { product_name: 'Complejo Natural B', url_image: '~/workspace/app/assets/', catalog_price: 249.0, points: 10.15, product_line: 'Nutrilite'},
                { product_name: 'Nutri Fiber Powder Fibra en Polvo', url_image: '~/workspace/app/assets/', catalog_price: 359.0, points: 12.62, product_line: 'Nutrilite'},
                { product_name: 'Rhodiola', url_image: '~/workspace/app/assets/', catalog_price: 620.0, points: 21.79, product_line: 'Nutrilite'},
                { product_name: 'Daily 30', url_image: '~/workspace/app/assets/', catalog_price: 175.0, points: 6.15, product_line: 'Nutrilite'},
                { product_name: 'Daily 60', url_image: '~/workspace/app/assets/', catalog_price: 299.0, points: 10.51, product_line: 'Nutrilite'},
                { product_name: 'Double X', url_image: '~/workspace/app/assets/', catalog_price: 1145.0, points: 40.24, product_line: 'Nutrilite'},
                { product_name: 'Concentrado de Frutas y Vegetales', url_image: '~/workspace/app/assets/', catalog_price: 425.0, points: 14.94, product_line: 'Nutrilite'},
                { product_name: 'Bio C Plus Liberacion Prolongada', url_image: '~/workspace/app/assets/', catalog_price: 190.0, points: 6.68, product_line: 'Nutrilite'},
                { product_name: 'HSN', url_image: '~/workspace/app/assets/', catalog_price: 329.0, points: 11.56, product_line: 'Nutrilite'},
                { product_name: 'Lecitina - E', url_image: '~/workspace/app/assets/', catalog_price: 145.0, points: 5.10, product_line: 'Nutrilite'},
                { product_name: 'Multicaroteno Natural', url_image: '~/workspace/app/assets/', catalog_price: 420.0, points: 14.76, product_line: 'Nutrilite'},
                { product_name: 'Tri Iron Folic', url_image: '~/workspace/app/assets/', catalog_price: 229.0, points: 8.05, product_line: 'Nutrilite'},
                { product_name: 'Nutrilite Kids', url_image: '~/workspace/app/assets/', catalog_price: 189.0, points: 6.64, product_line: 'Nutrilite'},
                { product_name: 'Cal Mag D Advanced', url_image: '~/workspace/app/assets/', catalog_price: 299.0, points: 10.51, product_line: 'Nutrilite'},
                { product_name: 'Concentrado de Frutas y Vegetales Masticable', url_image: '~/workspace/app/assets/', catalog_price: 199.0, points: 10.90, product_line: 'Nutrilite'},
                { product_name: 'Acerola C Masticable', url_image: '~/workspace/app/assets/', catalog_price: 199.0, points: 6.99, product_line: 'Nutrilite'},
                { product_name: 'Black Cohosh', url_image: '~/workspace/app/assets/', catalog_price: 459.0, points: 16.13, product_line: 'Nutrilite'}])
